version: 2
updates:
  # Update npm dependencies for the npm package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    groups:
      react-and-related:
        patterns:
          - "react"
          - "react-dom"
          - "@testing-library/react"
