"use client";

    import React from "react";

    // generated by rpd-cli
    import Demo from "react-pkg-demo";
    

    function HomePage({ content }: { content: string }) {

      return (
        <Demo
          color="#bfe0ea"
          packageName={"rapid-react-pkg-demo"}
          description={"A CLI tool for quickly creating react package demos"}
          icon={"🌊"}
          
          markdown={content}
        />
      );
    }

    export default HomePage;
    