"use client";

  import React from "react";

  // generated by rpd-cli
  import Demo from "react-pkg-demo";
  

  function HomePage({ content }: { content: string }) {

    return (
      <Demo
        color="#bfe0ea"
        packageName={"rapid-react-pkg-demo"}
        icon={"🌊"}
        
        markdown={content}
      />
    );
  }

  export default HomePage;
  